apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
stringData:
  root-password: "123456"
  user: "mysite3"
  user-password: "123456"
  host: "mysql1.default.svc.luowei.com"
  database: "mysite3"
