apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
stringData:
  mysql-root-password: "123456"
  mysql-user: "mysite3"
  mysql-password: "123456"
  mysql-host: "mysql1.default.svc.luowei.com"
  mysql-database: "mysite3"
