apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  # 值必须用 base64 编码：echo -n 'value' | base64
  mysql-root-password: 123456
  mysql-user: mysite3
  mysql-password: 123456
  mysql-host: mysql1.default.svc.luowei.com
  mysql-database: mysite3
