# Generated by Django 5.1.6 on 2026-04-05 05:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('age', models.IntegerField(default=1, verbose_name='年龄')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='邮箱')),
                ('country', models.CharField(default='中国', max_length=50, verbose_name='国家')),
                ('bio', models.TextField(blank=True, verbose_name='简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
                'db_table': 'author',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegacyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('identity_info', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='LegacyShu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('title', models.CharField(default='', max_length=50, verbose_name='书名')),
                ('pub', models.CharField(default='', max_length=100, verbose_name='出版社')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='价格')),
                ('market_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='零售价')),
                ('record', models.CharField(default='', max_length=100, verbose_name='登记人')),
                ('record_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('shu_nub', models.IntegerField(default=1, verbose_name='数量')),
                ('author11_name', models.CharField(default='', max_length=11, verbose_name='作者')),
                ('shu_jia', models.CharField(default='杂学书架', max_length=20, verbose_name='书架')),
            ],
            options={
                'db_table': 'shu',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('author_name', models.CharField(default='', help_text='如果未选择作者，可直接填写作者名', max_length=100, verbose_name='作者名称')),
                ('publisher', models.CharField(max_length=200, verbose_name='出版社')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='出版日期')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='零售价')),
                ('category', models.CharField(choices=[('fiction', '小说'), ('science', '科学'), ('technology', '技术'), ('history', '历史'), ('art', '艺术'), ('education', '教育'), ('other', '其他')], default='other', max_length=20, verbose_name='分类')),
                ('shelf_location', models.CharField(default='A-1-1', max_length=50, verbose_name='书架位置')),
                ('total_copies', models.PositiveIntegerField(default=1, verbose_name='总库存')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='可借数量')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('record', models.CharField(default='', max_length=100, verbose_name='登记人')),
                ('record_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可借')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookstore.author', verbose_name='作者')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'db_table': 'book',
                'ordering': ['-record_time'],
            },
        ),
        migrations.CreateModel(
            name='LegacyCusstom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1111)),
                ('age', models.IntegerField(default=1, verbose_name='年龄')),
                ('iden_type', models.CharField(max_length=1111, verbose_name='证件类型')),
                ('iden', models.CharField(max_length=18, verbose_name='身份证信息')),
                ('contact_details', models.CharField(max_length=11, null=True, verbose_name='联系方式')),
                ('reader_type', models.CharField(max_length=1111, verbose_name='读者类型')),
                ('jie_num', models.PositiveIntegerField(default=1, verbose_name='借书数量')),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='借书时间')),
                ('due_date', models.DateField(verbose_name='应还书时间')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='归还时间')),
                ('returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_borrow_records', to='bookstore.legacyshu')),
            ],
            options={
                'db_table': 'Cusstom',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号')),
                ('reader_type', models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('staff', '职工'), ('guest', '访客')], default='student', max_length=20, verbose_name='读者类型')),
                ('max_borrow_count', models.PositiveIntegerField(default=5, verbose_name='最大借书数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reader_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '读者',
                'verbose_name_plural': '读者',
                'db_table': 'reader',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True, verbose_name='借书时间')),
                ('due_date', models.DateField(verbose_name='应还书时间')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='归还时间')),
                ('status', models.CharField(choices=[('borrowed', '借阅中'), ('returned', '已归还'), ('overdue', '已逾期'), ('lost', '已遗失')], default='borrowed', max_length=20, verbose_name='状态')),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='罚款金额')),
                ('fine_paid', models.BooleanField(default=False, verbose_name='罚款已付')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='bookstore.book', verbose_name='图书')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_borrows', to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='bookstore.reader', verbose_name='读者')),
            ],
            options={
                'verbose_name': '借阅记录',
                'verbose_name_plural': '借阅记录',
                'db_table': 'borrow_record',
                'ordering': ['-borrow_date'],
            },
        ),
    ]
